### PR TITLE
Unregister events when window is unloading

### LINKED ISSUE #546: events registered on blackberry.event are fired once for every page refresh/navigation
Whenever an app navigates or refreshes the webview any event fired from `blackberry.event` will fire an additional time.  This makes it really hard to use the pause and resume events.

Steps to reproduce:
1. build the attached app
2. Note that webworksready was fired
3. pause and resume the app (switch apps on the device, or just get it into the tile mode)
4. note that the counts for pause and resume are both 1
5. press the refresh button
6. note the counts are now both zero
7. pause and resume the app
8. Note the count is now 2 for pause and resume (UNEXPECTED)

Test App:

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    Refresh the page (to simulate inapp navigation)
    <h1 id="ready_count">webworksready was fired 0 times</h1>
    <h1 id="pause_count">pause was fired 0 times</h1>
    <h1 id="resume_count">resume was fired 0 times</h1>

    <button id="refresh" onclick='location.reload();'>Refresh</button>
    <script type="text/javascript" src="local:///chrome/webworks.js"></script>
    <script type="text/javascript">
        var ready = 0, pause = 0, resume = 0;

        document.addEventListener('webworksready', function () {
            var wwr = document.getElementById('ready_count');
            wwr.innerText = 'webworksready was fired ' + ++ready + ' times';

            blackberry.event.addEventListener('pause', function () {
                var el = document.getElementById('pause_count');
                el.innerText = 'Pause was fired ' + ++pause + ' times';
            });

            blackberry.event.addEventListener('resume', function () {
                var el = document.getElementById('resume_count');
                el.innerText = 'Resume was fired ' + ++resume + ' times';
            });
        });
    </script>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by gtanner**
Fixes #546

```
Keep a list of events that are registered and on beforeunload
call removeEventListener for each of them.

There is no need to worry about if the user calls remove since
calling remove with an event and func that doesn't exist does
nothing, keeps the code simpler.  The same goes for worrying
about grouping / keeping track of duplicates since the extra
calls to remove does nothing.
```

### CODE REVIEW

**Comment by katwiththek** [comment]
```
                                                                                  Whoa Gord! You're still doing work on bb10-ww?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Gord TannerSent: Monday, August 31, 2015 9:29 PMTo: blackberry/BB10-WebWorks-FrameworkReply To: blackberry/BB10-WebWorks-FrameworkSubject: Re: [BB10-WebWorks-Framework] Unregister events when window is unloading (#603)Closed #603.
```

—Reply to this email directly or view it on GitHub.

**Comment by gtanner** [comment]
no ;)

Just saw my PR that was open since Feb 28th 2013, figured it should be closed.

**Comment by katwiththek** [comment]
```
                                                                                  Haha... Haven't heard that word PR for so long. :P                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Gord TannerSent: Monday, August 31, 2015 9:33 PMTo: blackberry/BB10-WebWorks-FrameworkReply To: blackberry/BB10-WebWorks-FrameworkCc: Kat LeungSubject: Re: [BB10-WebWorks-Framework] Unregister events when window is unloading (#603)no ;)
```

Just saw my PR that was open since Feb 28th, figured it should be closed.

—Reply to this email directly or view it on GitHub.

**Comment by gtanner** [comment]
:)

**Pull request closed without merging**
